server:
  port: 8580
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka,http://dmx:8881/eureka
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: world-consumer-feign
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
      username: root
      password: root
  redis:
    database: 0 # Redis数据库索引（默认为0)
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: root # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 10000 # 连接超时时间（毫秒）